name: VPS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update and upgrade
        run: sudo apt-get update -y && sudo apt-get upgrade -y
        
      - name: Run sshd
        run: sudo service sshd start
        
      - name: Change pass
        run: yes superpass | sudo passwd
        
      - name: add user
        run: |
          sudo useradd -m superuser
          yes superpass | sudo passwd superuser
          sudo usermod -aG sudo superuser

      - name: Run Serveo tunnel
        run: |
          ssh -R 80:localhost:22 serveo.net -o StrictHostKeyChecking=no -N &
        
      - name: Display Serveo URL
        run: sleep 5 && curl -s http://localhost:4040/api/tunnels || echo "Serveo URL should be available on the SSH client log."

      - name: run loop
        run: tail -f /dev/null
