name: VPS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update and upgrade
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: Run sshd
        run: sudo service sshd start
        
      - name: Change pass
        run: yes superpass | sudo passwd
        
      - name: add user
        run: |
          sudo useradd -m superuser
          yes superpass | sudo passwd superuser
          sudo usermod -aG sudo superuser

      - name: Run Serveo tunnel and save URL
        run: |
          ssh -R 0:localhost:22 serveo.net -o StrictHostKeyChecking=no -N > serveo_url.txt 2>&1 &
          sleep 5
          cat serveo_url.txt | grep -o ".*serveo.net"

      - name: Display Serveo URL
        run: cat serveo_url.txt | grep -o ".*serveo.net"
        
      - name: run loop
        run: tail -f /dev/null
