name: Create tmate Session

on: [push, workflow_dispatch]

jobs:
  create-tmate-session:
    runs-on: kygtps-vpsngrok-w9o9dbmi9nz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tmate
        run: sudo apt-get install -y tmate

      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
          echo "Web: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"
          tmate -S /tmp/tmate.sock display -p 'Web URL: #{tmate_web}'

      - name: Keep session alive
        run: sleep infinity
