name: VPS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Upgrade
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install LocalTunnel
        run: npm install -g localtunnel

      - name: Run sshd
        run: sudo service sshd start

      - name: Change Password
        run: echo -e "superpass\nsuperpass" | sudo passwd root

      - name: Add User
        run: |
          sudo useradd -m superuser
          echo -e "superpass\nsuperpass" | sudo passwd superuser
          sudo usermod -aG sudo superuser

      - name: Display External IP
        run: curl ifconfig.me

      - name: Start LocalTunnel
        run: |
          lt --port 22 > localtunnel.txt 2>&1 &
          curl https://loca.lt/mytunnelpassword
          sleep 5

      - name: Display LocalTunnel URL
        run: cat localtunnel.txt

      - name: Run loop
        run: tail -f /dev/null
